// Default need comms times in minutes for standard missions
export const needCommsMissionDefaults: Record<string, number> = {
  profile_station: 60,
  portuguese_ledge: 120,
  sci2: 60,
  sci2_backseat: 60,
  mbts_sci2: 60,
  keepstation: 45,
  ballast_and_trim: 45,
  keepstation_3km: 45,
  transit_3km: 30,
  transit: 30,
  CircleSample: 240,
  circle_sample: 240,
  CorkAndScrew: 60,
  profile_station_backseat: 60,
  IsothermDepthSampling: 60,
  location_depth_sampling: 60,
  LocationDepthSampling: 60,
  isotherm_depth_dampling: 60,
  esp_sample_at_depth: 180,
  esp_sample_station: 45,
  calibrate_sparton_compass: 60,
  SpartonCompassCal: 60,
  spiral_cast: 180,
  trackPatchChl_yoyo: 180,
  trackPatch_yoyo: 300,
  FrontSampling: 60,
  Smear: 60,
  front_sampling: 300,
  sci2_flat_and_level_backseat: 60,
}
